name: boost
description: "Memozen Boost"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Google
  firebase_ui_auth: ^1.16.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_analytics: ^11.3.5
  # Functional
  intl: ^0.19.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^8.0.2
  # Navigation
  go_router: ^14.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/common/
    - path: assets/admin/
      flavors:
        - admin_development
        - admin_staging
        - admin_production
